// Renders the bill as a document you can print or save as a PDF.
//
// The panel writes the summary to storage and opens this page. It is written
// to survive being forwarded: every figure names its inputs, and the caveats
// travel with it, because whoever opens the PDF never saw the extension.
"use strict";
(function () {
  var C = globalThis.PaisaConvert;
  var $ = function (id) { return document.getElementById(id); };

  function monthName(ym) {
    var p = String(ym || "").split("-").map(Number);
    if (!p[0] || !p[1]) return "";
    return new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(Date.UTC(p[0], p[1] - 1, 1)));
  }

  function nextMonthName(ym) {
    var p = String(ym || "").split("-").map(Number);
    if (!p[0] || !p[1]) return "next month";
    return new Intl.DateTimeFormat("en-IN", { month: "long", timeZone: "UTC" }).format(new Date(Date.UTC(p[0], p[1], 1)));
  }

  function row(tbody, label, value, cls) {
    var tr = document.createElement("tr");
    if (cls) tr.className = cls;
    var a = document.createElement("td");
    a.textContent = label;
    var b = document.createElement("td");
    b.textContent = value;
    tr.appendChild(a);
    tr.appendChild(b);
    tbody.appendChild(tr);
  }

  function render(s) {
    var b = s.breakdown;
    var st = s.settings;
    var inc = st.entity === "AWS_INC";

    document.title = "Paisa — AWS bill in rupees, " + monthName(s.month);
    $("period").textContent = monthName(s.month) + " · as of " + s.asOf + " (day " + s.daysElapsed + " of " + s.daysInMonth + ")";

    $("soFar").textContent = C.inr(b.total, 2);
    $("soFarNote").textContent = "AWS console shows " + C.usd(s.usd);
    $("projection").textContent = C.inr(s.projection, 2);
    $("projectionNote").textContent =
      "Includes " + C.pct(st.gst_pct, 0) + " GST" + (inc ? " and " + C.pct(st.markup_pct, 1) + " card markup" : "") +
      ". AWS issues it in early " + nextMonthName(s.month) + ".";

    var tb = $("breakdown");
    tb.textContent = "";
    row(tb, C.usd(s.usd) + " at " + C.inr(s.fx.rate, 2) + " per USD", C.inr(b.base, 2));
    row(tb, inc ? "Card forex markup, " + C.pct(st.markup_pct) : "Card forex markup — none (AISPL invoices in INR)", C.inr(b.markup, 2));
    row(tb, "GST, " + C.pct(st.gst_pct) + (inc ? " on base plus markup" : " on base"), C.inr(b.gst, 2));
    row(tb, "Total so far (estimate)", C.inr(b.total, 2), "total");

    if (s.services && s.services.length) {
      $("servicesBlock").hidden = false;
      var st2 = $("services");
      st2.textContent = "";
      s.services.forEach(function (svc) {
        var tr = document.createElement("tr");
        var a = document.createElement("td");
        a.textContent = svc.name;
        var c = document.createElement("td");
        c.textContent = C.inr(svc.inr, 2);
        var u = document.createElement("span");
        u.className = "usd";
        u.textContent = C.usd(svc.usd);
        c.appendChild(u);
        tr.appendChild(a);
        tr.appendChild(c);
        st2.appendChild(tr);
      });
      if (s.otherUsd > 0.005) {
        var tr2 = document.createElement("tr");
        var a2 = document.createElement("td");
        a2.textContent = "Everything else";
        var c2 = document.createElement("td");
        c2.textContent = C.inr(s.otherInr, 2);
        tr2.appendChild(a2);
        tr2.appendChild(c2);
        st2.appendChild(tr2);
      }
    }

    $("caveat").textContent =
      "Every figure here is an estimate. The exchange rate is a mid-market rate" +
      (s.fx.source ? " from " + s.fx.source : "") +
      (s.fx.fetchedAt ? ", fetched " + String(s.fx.fetchedAt).slice(0, 10) : "") +
      "; your bank converts at its own rate on the settlement date, which will differ. The card markup of " +
      C.pct(st.markup_pct) + " and GST of " + C.pct(st.gst_pct) +
      " are the settings chosen in Paisa, not figures read from AWS — your card issuer and your AWS entity decide the real amounts.";

    $("footer").textContent =
      "Generated by Paisa on " + new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) +
      (s.fromPage ? ". Read from the figure shown in the AWS console." : ". Read from AWS cost data via a read-only role.") +
      " Paisa is not affiliated with Amazon Web Services.";
  }

  function fail(message) {
    $("period").textContent = message;
    $("caveat").textContent = "Open the ₹ Bill panel on your AWS console first, then choose Save as PDF.";
  }

  chrome.storage.local.get({ report: null }, function (d) {
    if (!d.report) return fail("No report to show.");
    try {
      render(d.report);
    } catch (e) {
      fail("That report could not be rendered.");
      return;
    }
    $("save").addEventListener("click", function () { window.print(); });
    $("close").addEventListener("click", function () { window.close(); });
    // Straight to the print dialog: "Save as PDF" is the destination there.
    setTimeout(function () { window.print(); }, 400);
  });
})();
