version = 0.1

[default.global.parameters]
stack_name = "paisa"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
resolve_s3 = true
confirm_changeset = true
disable_rollback = false
